name = "necheleslaw-contact"
main = "src/index.js"
compatibility_date = "2026-06-10"

routes = [
  { pattern = "necheleslaw.com/contact-submit", zone_name = "necheleslaw.com" },
  { pattern = "www.necheleslaw.com/contact-submit", zone_name = "necheleslaw.com" }
]

[vars]
ALLOWED_ORIGINS = "https://necheleslaw.com,https://www.necheleslaw.com"
CONTACT_FROM = "Necheles Law Website <contact@necheleslaw.com>"
